#!/bin/bash
adb shell pm uninstall --user 0 com.huawei.hifolder
adb shell pm uninstall --user 0 com.huawei.android.tips
adb shell pm uninstall --user 0 com.android.mediacenter
adb shell pm uninstall --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall --user 0 com.android.providers.calendar
adb shell pm uninstall --user 0 com.huawei.health
adb shell pm uninstall --user 0 com.huawei.hidisk
adb shell pm uninstall --user 0 com.huawei.hiview
adb shell pm uninstall --user 0 com.android.hwmirror
adb shell pm uninstall --user 0 com.huawei.KoBackup
adb shell pm uninstall --user 0 com.huawei.hiviewtunnel
adb shell pm uninstall --user 0 com.hisi.mapcon
adb shell pm uninstall --user 0 com.android.frameworkhwext.honor
adb shell pm uninstall --user 0 com.huawei.imedia.sws
adb shell pm uninstall --user 0 com.huawei.hwid
adb shell pm uninstall --user 0 com.huawei.tips
adb shell pm uninstall --user 0 com.gameloft.android.GloftANPH
adb shell pm uninstall --user 0 com.gameloft.android.GloftDBMF
adb shell pm uninstall --user 0 com.gameloft.android.GloftDMKF
adb shell pm uninstall --user 0 com.gameloft.android.GloftPDMF
adb shell pm uninstall --user 0 com.gameloft.android.GloftSMIF
adb shell pm uninstall --user 0 com.android.frameworkhwext.dark
adb shell pm uninstall --user 0 com.android.egg
adb shell pm uninstall --user 0 com.huawei.android.instantshare
adb shell pm uninstall --user 0 com.huawei.indexsearch.observer
adb shell pm uninstall --user 0 com.huawei.indexsearch
adb shell pm uninstall --user 0 com.huawei.hwasm
adb shell pm uninstall --user 0 com.android.dreams.basic
adb shell pm uninstall --user 0 com.hicloud.android.clone
adb shell pm uninstall --user 0 com.huawei.HwMultiScreenShot
adb shell pm uninstall --user 0 com.huawei.vassistant
adb shell pm uninstall --user 0 com.google.android.syncadapters.contact
adb shell pm uninstall --user 0 com.huawei.android.instantonline
adb shell pm uninstall --user 0 com.huawei.android.totemweatherapp
adb shell pm uninstall --user 0 com.huawei.android.projectmenu
adb shell pm uninstall --user 0 com.huawei.scanner
adb shell pm uninstall --user 0 com.huawei.hwdetectrepair
adb shell pm uninstall --user 0 com.huawei.android.karaoke
adb shell pm uninstall --user 0 com.huawei.lbs
adb shell pm uninstall --user 0 com.huawei.iaware
adb shell pm uninstall --user 0 com.huawei.android.chr
adb shell pm uninstall --user 0 com.huawei.android.hsf
adb shell pm uninstall --user 0 com.google.android.ext.shared
adb shell pm uninstall --user 0 com.android.wallpapercropper
adb shell pm uninstall --user 0 com.huawei.nearby
adb shell pm uninstall --user 0 com.huawei.android.FloatTasks
adb shell pm uninstall --user 0 com.huawei.motionservice
adb shell pm uninstall --user 0 com.huawei.appmarket
adb shell pm uninstall --user 0 com.huawei.recsys
adb shell pm uninstall --user 0 com.huawei.android.totemweather
adb shell pm uninstall --user 0 com.huawei.gameassistant
adb shell pm uninstall --user 0 com.huawei.trustcircle
adb shell pm uninstall --user 0 com.huawei.himovie.overseas
adb shell pm uninstall --user 0 com.android.partnerbrowsercustomizations.tmobile
adb shell pm uninstall --user 0 com.huawei.videoeditor
adb shell pm uninstall --user 0 com.huawei.iconnect
adb shell pm uninstall --user 0 com.huawei.watch.sync
adb shell pm uninstall --user 0 com.huawei.hwstartupguide
adb shell pm uninstall --user 0 com.google.android.partnersetup
adb shell pm uninstall --user 0 com.huawei.fido.uafclient
adb shell pm uninstall --user 0 com.huawei.android.mirrorshare
adb shell pm uninstall --user 0 com.huawei.contactscamcard
adb shell pm uninstall --user 0 com.google.android.feedback
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall --user 0 com.huawei.hicloud
adb shell pm uninstall --user 0 com.huawei.android.totemweatherwidget
adb shell pm uninstall --user 0 com.android.dreams.phototable
adb shell pm uninstall --user 0 com.huawei.android.dsdscardmanager
adb shell pm uninstall --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall --user 0 com.huawei.android.hwaps
adb shell pm uninstall --user 0 com.huawei.android.wfdft
adb shell pm uninstall --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall --user 0 com.huawei.mmitest
adb shell pm uninstall --user 0 com.qeexo.smartshot

#This installs FDroid, the Nova Launcher, and AnySoftKeyboard. Remove the hashtags to install them!
#adb install FDroid.apk
#adb install nova.apk
#adb install anysoftkeyboard.apk

# Remove the hashtags on each line to also remove the following:

# GOOGLE APPS
#adb shell pm uninstall --user 0 com.google.android.youtube
#adb shell pm uninstall --user 0 com.google.android.ext.services
#adb shell pm uninstall --user 0 com.android.vending
#adb shell pm uninstall --user 0 com.google.android.apps.work.oobconfig
#adb shell pm uninstall --user 0 com.google.android.gm
#adb shell pm uninstall --user 0 com.google.android.apps.tachyon
#adb shell pm uninstall --user 0 com.google.android.music
#adb shell pm uninstall --user 0 com.google.android.apps.docs
#adb shell pm uninstall --user 0 com.google.android.apps.maps
#adb shell pm uninstall --user 0 com.android.chrome
#adb shell pm uninstall --user 0 com.google.android.backuptransport
#adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.docs
#adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.sheets
#adb shell pm uninstall --user 0 com.google.android.apps.docs.editors.slides
#adb shell pm uninstall --user 0 com.google.android.apps.photos
#adb shell pm uninstall --user 0 com.google.android.syncadapters.calendar
#adb shell pm uninstall --user 0 com.google.android.videos


# BASIC APPS YOU MIGHT WANT TO KEEP

#adb shell pm uninstall --user 0 com.android.contacts
#adb shell pm uninstall --user 0 com.android.calendar
#adb shell pm uninstall --user 0 com.example.android.notepad
#adb shell pm uninstall --user 0 com.android.wallpaperbackup
#adb shell pm uninstall --user 0 com.touchtype.swiftkey
#adb shell pm uninstall --user 0 com.swiftkey.swiftkeyconfigurator
#adb shell pm uninstall --user 0 com.huawei.android.launcher
#adb shell pm uninstall --user 0 com.huawei.powergenie
#adb shell pm uninstall --user 0 com.huawei.android.thememanager
#adb shell pm uninstall --user 0 com.huawei.android.FMRadio
#adb shell pm uninstall --user 0 com.android.soundrecorder
#adb shell pm uninstall --user 0 com.huawei.compass


# SERVICE APPS

#adb shell pm uninstall --user 0 com.booking
#adb shell pm uninstall --user 0 com.ebay.mobile
#adb shell pm uninstall --user 0 com.instagram.android
#adb shell pm uninstall --user 0 com.facebook.appmanager
#adb shell pm uninstall --user 0 com.facebook.katana
#adb shell pm uninstall --user 0 com.facebook.system
#adb shell pm uninstall --user 0 com.ebay.carrier
#adb shell pm uninstall --user 0 com.netflix.partner.activation
#adb shell pm uninstall --user 0 com.netflix.mediaclient
